const projects = [
  {
    name: "Insane in the Brain: Cypress Hill",
    coverImg: "",
    images: [""],
    description: "Showtime Documentary Film",
    tags: ["Key Art",
    "Creative Direction",
    "Copy Direction",
    "Retouching & Finishing",
    "Title Treatment",
    "Motion & Animation",
    "Print & Digital OOH"],
  },
  {
    name: "Flatbush Misdemeanors",
    coverImg: "",
    images: [""],
    description: "Season 1 | Showtime",
    tags: ["Key Art",
    "Creative Direction",
    "Concept Development",
    "Character Campaign",
    "Retouching",
    "Icon Design",
    "Title Treatment",
    "Motion Design",
    "Print Marketing",
    "Photoshoot Art Direction",
    "Billboards & Digital OOH"
    ],
    photography: "Grace Rivera",
    photographyLink: "",
    artDirection: "",
    artDirectionLink:"",
  },
]